### ISSUE TITLE
Code for reproducing 2d experiments

### ISSUE THREAD

**Issue by ducminhkhoi** [cambridge-mlg/convcnp#1]
Thanks for sharing your fantastic work. Do you have any plan to release the code for 2d experiments? 

Thanks,

**Comment by YannDubs** [comment]
Hi, these will be released soon after the NeurIPS deadline (beginning of June). They will be in an other repo but we will will link it here. I'm keeping the issue open until then :)

**Comment by YannDubs** [comment]
Sorry I forgot about this issue, you can find all the necessary code here : https://yanndubs.github.io/Neural-Process-Family/reproducibility/ConvCNP.html
