### ISSUE TITLE
rbf kernel in the 1-d experiment

### ISSUE THREAD

**Issue by thjashin** [cambridge-mlg/convcnp#2]
Hi authors,

Congratulations on your work! I really enjoyed it.
During playing with the code, I found that the rbf kernel used for the 1-d regression experiments has two lengthscales parameters (and thus two outputs):
```python
self.sigma = nn.Parameter(np.log(init_length_scale) *
                                  torch.ones(self.in_channels), requires_grad=True)

def rbf(self, dists):
        scales = self.sigma_fn(self.sigma)[None, None, None, :]
        a, b, c = dists.shape
        return torch.exp(-0.5 * dists.view(a, b, c, -1) / scales ** 2)
```
which I don't understand. 
It seems that \psi is a scalar-valued function according to the paper?

**Comment by wesselb** [comment]
Dear @thjashin,

Thank you for your interest! :)

The kernel `\psi` is indeed a scalar-valued function. However, the functional embedding consists of two "channels": the data channel and density channel. This means that there are two summations against `\psi`. In the code, we let `\psi` have a different length scale for every channel (data and density). Hence, the two length scales do not correspond to different input dimensions, but to different channels.

Hopefully this clarifies a little. Please do let me know if anything is still unclear.

**Comment by thjashin** [comment]
Hi @wesselb ,

That makes sense! Thank you for the clarification. I still wonder if such choice matters. It seems that from the theory a shared lengthscale is sufficient?

Just one more question, can you explain how you actually applied a trained ConvCNP (218 × 178) to images of size (337 × 599), do you simply keep all the conv filters and apply them to the larger image?

**Comment by wesselb** [comment]
Dear @thjashin,

You're right that a shared length scale should suffice. Having different length scales, however, may help with the non-asymptotics of the problem, e.g. how quickly model learns.

And you're also right on your second point! The ConvCNP is applicable to 1D data sets of varying sizes and images of varying sizes by keeping the conv filters and applying them to larger discretisations or images.
