### ISSUE TITLE
How to generalise the ConvCNP on a new dataset

### ISSUE THREAD

**Issue by lanfeiying** [cambridge-mlg/convcnp#4]
Hi, 
Thank you for your excellent work and this open-source project!
I am using ConvCNP for meta-learning and I encountered two questions.

Q1:
I trained the ConvCNP on the default oracle GP and test it on a number of new context points. If the new context points are generated from the original oracle GP, the prediction from ConvCNP is consistent with the oracle GP. However, if I test the ConvCNP on new context points generated by another non-zero mean GP, that is, the context data points are away from 0. 
The prediction of ConvCNP tends to drag the prediction and uncertainties back to zero-mean, or even doesn't work on the new context points. 
![question_figure1](https://user-images.githubusercontent.com/22729258/163226737-4ce010ee-9118-4eb3-90ed-ba8c26b202d7.png)
![question_figure2](https://user-images.githubusercontent.com/22729258/163226751-3752a33c-6232-420e-87cf-cdb1ef4f8cbd.png)

So, the question is, am I doing something wrong? Does the trained ConvCNP model only work for the dataset generated by Oracle GP?

Q2:
I have another question about the prediction. If I only have a fixed dataset $D = {(x_1, y_1), (x_2, y_2), ..., (x_n, y_n)}$, can I train the ConvCNP on this fixed dataset D without data generated from oracle GP and obtain a ConvCNP model equivalent to a GP model on D?

**Comment by wesselb** [comment]
Dear @lanfeiying,

First of all, thank you for opening an issue on the repo. We're excited that you're trying out the ConvCNP! :)

Q1:

Although the predictions by the ConvCNP look weird and perhaps pathological, we believe that the behaviour is correct, despite obviously being undesirable. What's going wrong is that the ConvCNP is trying to mimic to the posterior of the GP you used during training. Importantly, this GP (1) has a short length scale of 1 and (2) has mean zero. As a consequence, the posterior of this GP and therefore the ConvCNP will think that all these non-zero-mean observations are too high, which pulls the prediction back to zero. Moreover, the length scale of your data looks much longer 1.

What we would suggest is that you (1) remove the mean of the data before running it through the ConvCNP, and (2) train the ConvCNP on data from a GP with a longer length scale. This will prevent the predictions from reverting to zero so quickly.

Q2:

Unfortunately, it is not possible to the ConvCNP on a single data set, unless you can reasonably split up that data set into many other data sets. You will therefore need to train the ConvCNP on other data before applying it to your data set. For example, see Experiment 5.3 from the ConvCNP paper, where we train the ConvCNP on simulated data and then apply it to real data, a setting called sim-to-real.

Best,

Wessel and James

**Comment by lanfeiying** [comment]
Dear Wessel and James,
Thank you for your prompt reply! It is very helpful to me!

I have a question about using a smaller length scale for the oracle GP. Should I stretch the kernel function `stheno.EQ().stretch(c)` to adjust the length scale for the oracle GP? I didn't find the documentation for this function on stheno's site. 
Thank you!

Regards,
Feiying

**Comment by wesselb** [comment]
Dear @lanfeiying,

Np at all. :)

> I have a question about using a smaller length scale for the oracle GP. Should I stretch the kernel function stheno.EQ().stretch(c) to adjust the length scale for the oracle GP? I didn't find the documentation for this function on stheno's site.

That's right! It's a bit hidden in the documentation, but Stheno uses [MLKernels](https://github.com/wesselb/mlkernels), which describes how to adjust the length scale of kernels [here](https://github.com/wesselb/mlkernels#compositional-design).

Here's an example:

```python
>>> from stheno import EQ

>>> EQ()
EQ()

>>> EQ().stretch(2)  # Change length scale to 2
EQ() > 2
```

**Comment by lanfeiying** [comment]
Dear Wessel,
Thank you very much for this information! 
Regards,
Feiying

**Comment by wesselb** [comment]
Dear @lanfeiying, no problem at all! Perhaps I should also point out that we're working on a more refined implementation of the ConvCNP in the package [neuralprocesses](https://github.com/wesselb/NeuralProcesses) (`pip install neuralprocesses`). Note that this is still a work in progress.

Here's an example of how you can construct a ConvCNP and run it forward:

```python
import lab as B
import torch

import neuralprocesses.torch as nps

convcnp = nps.construct_gnp(dim_x=1, dim_y=1, likelihood="het")
dist = convcnp(
    B.randn(torch.float32, 16, 1, 10),  # Context inputs
    B.randn(torch.float32, 16, 1, 10),  # Context outputs
    B.randn(torch.float32, 16, 1, 15),  # Target inputs
)
mean, var = dist.mean, dist.var  # Prediction for target outputs

# Compute various things:
print(dist.logpdf(B.randn(torch.float32, 16, 1, 15)))
print(dist.sample())
print(dist.kl(dist))
print(dist.entropy())
```

**Comment by lanfeiying** [comment]
Dear Wessel, 
Thank you very much for this information! This package includes many NP variants that I wanted and is very helpful to my work!
Regards,
Feiying
